name: express test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DOCKERHUB }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jakubjadczyk/my-image:latest